### ISSUE TITLE
Outdated address

### ISSUE THREAD

**Issue by Xavier59** [decentraland/contracts#16]
Hello,

A lot of address seems to be outdated.

For mainnet, eg : 
- LegacyMarketplace
- Marketplace 
- ...

Could you fix this ? What's the process to find the right address by myself to issue a pull requests ?

**Comment by nachomazzara** [comment]
Hey, how are you? 

The `LegacyMarketplace` and the `Marketplace` addresses are ok [here](https://github.com/decentraland/contracts/blob/gh-pages/addresses).

**Comment by Xavier59** [comment]
Thanks for your answer.
I don't get it, I've been browsing all smart contracts and I can't find any with recent event such as AuctionCancelled, AuctionSuccessful and AuctionCreated which made me assume the address wasn't updated.
Which smart contract is it ? Is there anywhere I can find documentation on the decentraland smart contracts ?

**Comment by nachomazzara** [comment]
The marketplace contract is here: https://github.com/decentraland/marketplace-contracts

We are using a proxy pattern, I recommend you to read about it. 

You should use the proxy address with the implementation ABI to get the events. 

The `LegacyMarketplace` is a single contract for the marketplace v1 and you should get events but from older blocks since the `Marketplace` contract with the proxy pattern represents the marketplace v2.

You can read more about the marketplace contracts here:

- Marketplace v1: https://github.com/decentraland/proposals/blob/master/dsp/dsp-0012/0012.md
- Marketplace v2: https://github.com/decentraland/proposals/blob/master/dsp/dsp-0013/0013.md
